### ISSUE TITLE
As a developer, I want to fix memory leaks, so I have a stable and working product in production.

### ISSUE THREAD

**Issue by glenflorendo** [yamovie/server#9] opened 2019-04-17 10:36 UTC
Heroku Logs:
`Warning: connect.session() MemoryStore is not designed for a production environment, as it will leak memory, and will not scale past a single process.`

**Comment by samsaksfithian** [comment] 2019-05-01 17:08
Moved to the yamovie/client issue list with the "back end" label, so that all the issues will be in the same backlog.

As such, this is now a duplicate of yamovie/client#195

**Closed as completed by samsaksfithian** 2019-05-01 17:08 UTC
Labels: bug, duplicate
