### ISSUE TITLE
As a developer I would like to seed new movies without having to re-seed the entire database.

### ISSUE THREAD

**Issue by hanshank** [yamovie/server#27] opened 2019-05-31 16:28 UTC
- I think that the seeding function has the potential to just make sure to not add duplicates, but keep adding new movies. That way we don't have to worry about the id's changing and messing with the watchlist/preferences that depend on the movie id's.

**Comment by samsaksfithian** [comment] 2019-05-31 17:18
Duplicate of yamovie/client#266

Moved to front end with the rest of the issues.

**Closed as completed by samsaksfithian** 2019-05-31 17:18 UTC
